### ISSUE TITLE
Increase Core Count on images-s

### ISSUE THREAD

**Issue by carrickr** [nulib/images#371] opened 2017-03-07 19:50 UTC
Images-s currently only has four cores and when testing image upload abilities these cores end up maxxed out by Image Magick conversions.  This makes the machine extremely unresponsive, multiple minute load times in the web app, etc.  We need more cores, at least temporarily, added to images-s so that our new version of it can be end to end testing.

Also while not as important, more RAM might also be useful, right now 11 GB is used on the machine during conversion, so we're still reasonable under the cap, but increased testing activity might push us over.

Ideally 4 more cores and another 4 GB of RAM to support the additional projected ImageMagick threads would be useful.

**Comment by davidschober** [comment] 2017-03-07 19:52
@d-venckus can we put in a request for more cores on images-s? Is that just a request to NUIT?

**Comment by d-venckus** [comment] 2017-03-07 23:40
Since this server is hosted in our vCloud segment, I can configure CPU cores and memory myself.  But I'll need to check on how much of a load exists upon its host server, since over-allocation of CPU would actually degrade performance at peak times, and not enhance it.  I'll check and get back to you.

**Comment by davidschober** [comment] 2017-03-08 14:43
Thanks @d-venckus @carrickr and team, can you followup?

**Comment by kdid** [comment] 2017-03-14 15:27
@d-venckus - could we get an update on this? 

Thanks.

**Comment by d-venckus** [comment] 2017-03-15 18:16
I checked, and I believe we should be able to sustain the additional cores.  I just reconfigured images-s, which I previously enabled for hot-add of cpu and memory, so we now are running with 8 vCPUs and 20 GB of memory.  If we run into any performance issues on the host, we might need to dial back a bit, but right now, performance looks fine.

**Comment by davidschober** [comment] 2017-03-15 18:19
Thanks!

**Comment by d-venckus** [comment] 2017-03-15 18:19
Please let me know how the VM performs under load, with the extra vCPUs and memory.

**Comment by davidschober** [comment] 2017-03-15 18:26
Closing.

**Comment by kdid** [comment] 2017-03-16 16:19
@d-venckus ( @davidschober ), after attempting to run through regression testing on Images-s, Erin is reporting performance is so slow that the system is unusable for testing. Is there anything else that can be done to boost performance?

**Comment by d-venckus** [comment] 2017-03-16 16:22
That's an unhappy thing.  Perhaps we might reboot the VM?  I "hot-added" CPU and memory, so maybe a reboot will improve performance.

**Comment by davidschober** [comment] 2017-03-20 13:50
closing as complete.

**Closed by davidschober** 2017-03-20 13:50 UTC
Labels: devops, staging
