### ISSUE TITLE
batch import - duplicate accession errors occurring without being actual duplicates

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#345] opened 2016-12-12 20:37 UTC
### Severity

Is the production site running?
- [x] yes
- [ ] no

Are staff blocked from performing their work?
- [x] yes
- [ ] no

### Descriptive summary

During batch ingest, my test files on staging are being rejected with this error "RuntimeError: Existing image found with this accession number:"  It doesn't matter what I make the accession number it rejects it out of hand. I also noticed that before it rejects the accession number that it first throws a "undefined method `attribute_method_matcher' for nil:NilClass" error which then changes to the runtime error.

first error:

![2016-12-12_142722](https://cloud.githubusercontent.com/assets/2250501/21115689/25cf6610-c078-11e6-873d-f794f1a2ecec.jpg)

changes into:

![2016-12-12_142857](https://cloud.githubusercontent.com/assets/2250501/21115685/1bda75fa-c078-11e6-9bed-1572854ac389.jpg)

### Expected behavior

Batch ingest ingests.

### Actual behavior

Batch ingest throwing runtime errors.

### Steps to reproduce the behavior

1. Try batch importing either "jy_test" or "jy_afri_small" in the batches folder

**Comment by davidschober** [comment] 2016-12-12 21:42
@jenyoung it looks like this is because there are works with the same accession number. I was able to import a batch using  a unique accession number https://images-s.library.northwestern.edu/multiresimages/inu:dil-0d8eab74-72da-4a25-b28f-3d104ac72b9d

I think we can close this assuming that we complete #344.

**Comment by jenyoung** [comment] 2016-12-12 21:58
But I'm using accession numbers that I know are not duplicates.

Sent by MailWise<http://www.mail-wise.com/installation/2> – See your emails as clean, short chats.


-------- Original Message --------

**Comment by kdid** [comment] 2016-12-13 18:33
@jenyoung I was able to reproduce your problem using a copy of your xml/tif in `jy_afri_small`. 

The xml is failing to add the update the relationSet in the work vra, and it is producing an incomplete  VRAWork file.  (that is why on retries it is failing with duplicate accession numbers, as the incomplete work record is not being removed)

I was able to get your xml file to work by adding (and the XML David tested yesterday contained it):

```
      <!--Relation-->
      <vra:relationSet>
         <vra:relation pref="true" type="imageOf" relids=""/>
      </vra:relationSet>
```

Is the relationSet XML something you normally include in your xml when doing a batch ingest?

**Comment by jenyoung** [comment] 2016-12-13 18:38
Yes it is. And my XSLT is supposed to be adding it to the records. I didn't realize it wasn't.  I will fix.

**Comment by davidschober** [comment] 2016-12-13 18:59
@jenyoung can you put this in a gotcha somewhere?

**Comment by davidschober** [comment] 2017-01-09 18:40
@kdid you have a different issue tracking documentation, so we can close this, correct?

**Closed** 2017-01-09 19:48 UTC
Labels: high priority, in review, staging
