### ISSUE TITLE
images-p: Publish from menu and batch import intermittently failing with   - "Error occurred during initialization of VM. Could not reserve enough space for object heap"

### ISSUE THREAD

**Issue by kdid** [nulib/images#305] opened 2016-09-23 16:49 UTC
## Descriptive summary

We have observed errors in the logs that correlate with failed publishes from Menu to images, and with failed batch import jobs indicating that JHOVE does not have enough memory to run on images-p. 
### Observed behavior

Errors in `/var/www/dil_hydra/shared/log/sidekiq.log` during batch import:

```
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
2016-09-22T18:57:52.634Z 8832 TID-ox3z1002w MultiresimagesBatchWorker JID-c297203a09209cb08adebf20 INFO: fail: 23.492 sec
```

Errors in `/var/www/dil_hydra/shared/log/production.log` during failed menu publish, indicating problem with JHOVE:

```
I, [2016-09-22T17:12:15.991745 #53366]  INFO -- : Checking for existing image...
I, [2016-09-22T17:12:18.452308 #53366]  INFO -- : Deleting work and image because Error when running JHOVE against /images_dropbox/11735/11735_320403.tif
```

Content of JHOVE file itself indicates cause of error:

```
[deploy@images-p 11735]$ cat /images_dropbox/11735/jhove_output.xml 
Error occurred during initialization of VM
Could not reserve enough space for object heap
```

We also see this error intermittently directly querying the java version on images-p (so don't think the error is related to JHOVE itself)

```
[deploy@images-p log]$ java -version 
Error occurred during initialization of VM 
Could not reserve enough space for object heap Error: Could not create the Java Virtual Machine. Error: A fatal exception has occurred. Program will exit.
```

Our initial guess is that this may correlated to the heavy resource consumption by the riiif conversion during page views of uncached images.

![screen shot 2016-09-26 at 8 36 47 am](https://cloud.githubusercontent.com/assets/6372022/18836801/2930abc2-83c7-11e6-8242-2eceaffc4fc7.png)

**Comment by davidschober** [comment] 2016-09-23 20:26
@Toputnal and @d-venckus we're going to need your insight on this. I know Venkus was going to install varnish as a test, which may protect the machine enough.  But do you have any other ideas? We can talk more Monday.

**Comment by davidschober** [comment] 2016-09-26 21:08
Per @d-venckus this seems to have been caused by conflicting Java versions. He uninstalled then reinstalled by hand. Should be mirrored in Puppet configs.

**Comment by davidschober** [comment] 2016-09-26 21:08
Can we validate?

**Comment by davidschober** [comment] 2016-11-03 19:04
@kdid @bmquinn @d-venckus Is this still an issue?

**Comment by kdid** [comment] 2016-11-03 19:05
@davidschober , yes still an intermittent issue.

**Comment by davidschober** [comment] 2016-11-03 19:06
@d-venkus can you dig into it a bit more and report?

**Comment by carrickr** [comment] 2017-03-06 15:39
Updating java on this machine, but it may introduce more bugs and break other aspects of the images environment.  Developers move we close this and only reopen if it becomes a significant problem and worth taking on the risk of the java update.

**Closed** 2017-03-06 15:39 UTC
Labels: bug, in review, production

**Comment by davidschober** [comment] 2017-03-06 18:26
agreed.
