### ISSUE TITLE
Titles with "Untitled" in DIL

### ISSUE THREAD

**Issue by egilchrist** [nulib/images#424] opened 2017-08-21 15:11 UTC
### Severity

Is the production site running?
- [X ] yes
- [ ] no

Are staff blocked from performing their work?
- [ ] yes
- [X ] no

### Descriptive summary
Many of the objects with a title of "Untitled" actually have titles. Keyword search "Untitled"

This affects Primo.

Digital Image Library = 1683
 Include any relevant tracebacks if you're reporting a bug.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by davidschober** [comment] 2018-01-09 20:31
dupe of #413

**Closed as completed by davidschober** 2018-01-09 20:31 UTC
