### ISSUE TITLE
null error happening when trying to publish to images

### ISSUE THREAD

**Issue by jenyoung** [nulib/images#303] opened 2016-09-22 21:16 UTC
**Expected behavior**
Images should publish to Images without errors.

**Actual behavior**
Images are being published to Images -- but throwing a null error.
This is for a brand new job. No saved metadata. Job:11741  -- 13 images, 5 of them threw the null error.
For the 5 that had the null error, Erin tried to publish them several times in MENU, until it finally did successfully publish them to Images. Upon successful publish, the images are removed from MENU.

error message:
![2016-09-13_113947](https://cloud.githubusercontent.com/assets/2250501/18766309/31bbe800-80df-11e6-98c5-4eb5a8d738e0.jpg)

**Steps to reproduce the behavior**
Edit metadata in a job
Publish image
Null error appears in MENU
Retry publishing until successful.
Search Images to find record.
### Related work
#296

**Comment by davidschober** [comment] 2016-09-23 13:42
jen or erin do you have the PIDs of the images that threw the null errors?

**Comment by davidschober** [comment] 2016-09-23 13:50
@jenyoung Can you take this job and see if we can reproduce the errors on Staging?

**Comment by davidschober** [comment] 2016-09-23 18:32
@jenyoung no need to reproduce this on staging it seems to be tied to #305. JHOVE is running out of memory.

**Comment by jenyoung** [comment] 2016-11-03 20:14
not every record that gets a "null" error eventually successfully publishes to MENU. Some never publish.

**Comment by davidschober** [comment] 2016-12-08 18:29
closing for now. This is tied to other issues we've dealt with.

**Closed** 2016-12-08 18:29 UTC
Labels: bug, on hold, production
